import { CompanyTariffs } from './types';

export const COMPANY_TARIFFS_LIST: CompanyTariffs[] = [
  {
    id: 1,
    nameCompany: 'Аэрофлот',
    tariffList: [
      {
        id: 1,
        nameTariff: 'Эконом',
        priceTariff: 4,
        maxWeight: 20,
        baggageLimit: true,
        baggageLimitsWeight: 5,
        baggagePriceLess: 0,
        baggagePriceMore: 5000,
        ageLimit: false,
      },
      {
        id: 2,
        nameTariff: 'Продвинутый',
        priceTariff: 8,
        maxWeight: 50,
        baggageLimit: true,
        baggageLimitsWeight: 5,
        baggagePriceLess: 0,
        baggagePriceMore: 4000,
        ageLimit: true,
        ageLimitNum: 7,
        ageLimitDiscontWithBaggage: false,
        ageLimitDiscount: 0.3,
      },
      {
        id: 3,
        nameTariff: 'Люкс',
        priceTariff: 15,
        maxWeight: 50,
        baggageLimit: false,
        ageLimit: true,
        ageLimitNum: 16,
        ageLimitDiscontWithBaggage: false,
        ageLimitDiscount: 0.3,
      },
    ],
  },
  {
    id: 1,
    nameCompany: 'РЖД',
    tariffList: [
      {
        id: 1,
        nameTariff: 'Эконом',
        priceTariff: 0.5,
        maxWeight: 50,
        baggageLimit: true,
        baggageLimitsWeight: 15,
        baggagePriceLess: 0,
        baggagePriceMore: 50,
        baggagePricePerKG: true,
        ageLimit: true,
        ageLimitNum: 5,
        ageLimitDiscontWithBaggage: false,
        ageLimitDiscount: 0.5,
      },
      {
        id: 2,
        nameTariff: 'Продвинутый',
        priceTariff: 2,
        maxWeight: 60,
        baggageLimit: true,
        baggageLimitsWeight: 20,
        baggagePriceLess: 0,
        baggagePriceMore: 50,
        baggagePricePerKG: true,
        ageLimit: true,
        ageLimitNum: 8,
        ageLimitDiscontWithBaggage: false,
        ageLimitDiscount: 0.3,
      },
      {
        id: 3,
        nameTariff: 'Люкс',
        priceTariff: 4,
        maxWeight: 60,
        baggageLimit: false,
        ageLimit: true,
        ageLimitNum: 16,
        ageLimitDiscontWithBaggage: true,
        ageLimitDiscount: 0.2,
      },
    ],
  },
];
